spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/deliveryey
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:rootpassword}
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

docker:
  compose:
    readiness-timeout: 5m
